CREATE TABLE [dbo].[Book]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    [Title] NVARCHAR(150) NOT NULL,
[ISBNCode] NVARCHAR(100) NOT NULL,
 [AuthorId] INT NOT NULL, 
[GenreId] INT NOT NULL
);

ALTER TABLE Book 
ADD CONSTRAINT FK_Book_Author FOREIGN KEY (AuthorId) 
    REFERENCES Author (Id) 
    ON DELETE CASCADE
    ON UPDATE CASCADE
;


ALTER TABLE Book 
ADD CONSTRAINT FK_Book_Genre FOREIGN KEY (GenreId) 
    REFERENCES Genre (Id) 
    ON DELETE CASCADE
    ON UPDATE CASCADE
;

